spring:
  application:
    name: vnrail-api

  datasource:
    url: jdbc:postgresql://localhost:5432/vnrail_db?createDatabaseIfNotExist=true
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true